const properties = [
  {slug:'canyon-house',title:'Canyon House',city:'Los Angeles, CA',price:8400000,beds:5,baths:6,sqft:6120,type:'Private Estate',tag:'New offering',tone:'sunset',desc:'A tranquil modernist residence set above the city, where limestone, warm oak, and glass frame the canyon light.'},
  {slug:'north-star-penthouse',title:'North Star Penthouse',city:'New York, NY',price:12750000,beds:4,baths:4.5,sqft:4580,type:'Penthouse',tag:'Exclusive',tone:'night',desc:'A rare full-floor home with an intimate terrace and a sweeping skyline horizon.'},
  {slug:'solana-residence',title:'Solana Residence',city:'Miami, FL',price:5200000,beds:4,baths:5,sqft:3980,type:'Waterfront',tag:'For sale',tone:'water',desc:'Effortless coastal living with a calm palette and a water-facing garden.'},
  {slug:'montecito-retreat',title:'Montecito Retreat',city:'Santa Barbara, CA',price:6950000,beds:5,baths:5.5,sqft:5400,type:'Estate',tag:'Coming soon',tone:'grove',desc:'A private garden retreat shaped by long views, layered planting, and quiet materiality.'},
  {slug:'horizon-loft',title:'Horizon Loft',city:'Austin, TX',price:2950000,beds:3,baths:3,sqft:2860,type:'Residence',tag:'For sale',tone:'clay',desc:'An airy top-floor residence that brings the hill country into the heart of the city.'},
  {slug:'palma-courtyard',title:'Palma Courtyard',city:'Palm Springs, CA',price:3600000,beds:4,baths:4,sqft:3510,type:'Desert Home',tag:'For sale',tone:'palm',desc:'An architectural escape composed around a serene, sunlit courtyard.'}
];
const $ = s => document.querySelector(s);
const money = n => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0,notation:'compact'}).format(n);
const card = (p,large=false) => `<article class="property ${large?'property--large':''}"><a class="property-image tone-${p.tone}" href="/properties/${p.slug}" aria-label="View ${p.title}"><span>${p.tag}</span><button class="heart" aria-label="Save ${p.title}" onclick="event.preventDefault();this.classList.toggle('saved')">♡</button><em>View ↗</em></a><div class="property-meta"><p>${p.type} · ${p.city}</p><div><h3>${p.title}</h3><strong>${money(p.price)}</strong></div><small>${p.beds} beds &nbsp; / &nbsp; ${p.baths} baths &nbsp; / &nbsp; ${p.sqft.toLocaleString()} sq ft</small></div></article>`;
const footer = () => `<div class="footer-mark">AURELIA</div><div class="footer-grid"><div><a class="brand" href="/">AURELIA<span>ESTATES</span></a><p>Exceptional places.<br>Enduring value.</p></div><div><p class="eyebrow">Explore</p><a href="/properties">Properties</a><a href="/about">Our story</a><a href="/services">Services</a><a href="/journal">Journal</a></div><div><p class="eyebrow">Concierge</p><a href="mailto:hello@aurelia.demo">hello@aurelia.demo</a><a href="tel:+12125550184">+1 212 555 0184</a><p>New York · Los Angeles · Miami</p></div><form class="newsletter"><label for="news">A considered note, occasionally.</label><div><input id="news" type="email" placeholder="Email address" aria-label="Email address"><button aria-label="Subscribe">↗</button></div></form></div><div class="footer-bottom"><span>© 2026 Aurelia Estates · Demo content</span><button id="top">Back to top ↑</button><span>Privacy · Terms</span></div>`;
function home(){ return `<section class="hero"><div class="hero-scene"><div class="hero-sun"></div><div class="hero-house"><i></i><i></i><i></i></div></div><div class="hero-content"><p class="eyebrow">Los Angeles · Collection 01</p><h1><span>Exceptional homes.</span><span><i>Extraordinary</i> lives.</span></h1><div class="hero-bottom"><a class="line-link" href="/properties">Explore properties <b>↗</b></a><p>Scroll to discover <i></i></p><p>01 / 03</p></div></div></section>
<section class="statement section"><p class="eyebrow">Our philosophy</p><h2 class="fill-text">We represent remarkable homes and create meaningful connections between exceptional places and the people who belong in them.</h2><div class="statement-foot"><div class="architecture"></div><p>Every address has a point of view. Our role is to recognise it, articulate it, and introduce it to the right next chapter.</p></div></section>
<section class="section featured"><div class="section-head"><p class="eyebrow">Selected residences</p><a class="line-link" href="/properties">View all properties <b>↗</b></a></div><div class="feature-grid">${card(properties[0],true)}${card(properties[1])}${card(properties[2])}</div></section>
<section class="stories"><div class="stories-head"><p class="eyebrow">A sense of place</p><h2>Spaces to <i>live within.</i></h2></div><div class="story-track">${['Waterfront Residences','Urban Penthouses','Private Estates','Architectural Retreats'].map((x,i)=>`<article class="story tone-${['water','night','grove','clay'][i]}"><p>0${i+1} / 04</p><div><span>Curated collection</span><h3>${x}</h3><a href="/properties">Explore <b>↗</b></a></div></article>`).join('')}</div></section>
<section class="section search-section"><div><p class="eyebrow">Find your place</p><h2>Begin with a<br><i>feeling.</i></h2></div><form id="quick-search" class="search-form"><label>Location<select name="city"><option value="">All locations</option><option>Los Angeles, CA</option><option>New York, NY</option><option>Miami, FL</option></select></label><label>Property type<select name="type"><option value="">Any type</option><option>Private Estate</option><option>Penthouse</option><option>Waterfront</option></select></label><label>Minimum price<select name="price"><option value="0">Any price</option><option value="5000000">$5M+</option><option value="8000000">$8M+</option></select></label><button class="dark-btn">Search residences <b>↗</b></button></form></section>
<section class="section services"><div class="service-image tone-grove"></div><div><p class="eyebrow">The Aurelia practice</p><h2>Expertise, made <i>personal.</i></h2><div class="service-list">${['Buying Advisory','Property Marketing','Private Sales','Investment Guidance','Relocation','Property Valuation'].map((s,i)=>`<a href="/services"><span>0${i+1}</span>${s}<b>↗</b></a>`).join('')}</div></div></section>
<section class="destinations">${['Los Angeles','New York','Miami','Palm Springs'].map((x,i)=>`<a class="destination tone-${['sunset','night','water','palm'][i]}" href="/properties?location=${encodeURIComponent(x)}"><span>0${i+1}</span><h2>${x}</h2><p>Explore the market <b>↗</b></p></a>`).join('')}</section>
<section class="section stats"><p class="eyebrow">A record of trust <small>— demonstrative figures</small></p><div>${[['$1.2B+','Represented value'],['150+','Completed transactions'],['18','Years of experience'],['92%','Referral-led clients']].map(x=>`<article><strong>${x[0]}</strong><p>${x[1]}</p></article>`).join('')}</div></section>
<section class="founder"><div class="portrait tone-clay"></div><div><p class="eyebrow">A measured perspective</p><blockquote>“A home should ask something of you — and give you a great deal in return.”</blockquote><p>Founder Mara Vale leads a small, focused team known for discretion, instinct, and tireless attention to every detail.</p><a class="line-link" href="/about">Meet our team <b>↗</b></a></div></section>
<section class="journal section"><div class="section-head"><div><p class="eyebrow">The journal</p><h2>Notes on <i>place.</i></h2></div><a class="line-link" href="/journal">Read all stories <b>↗</b></a></div><div class="journal-grid">${['The quiet power of material restraint','A guide to living with the light','Where architecture meets the landscape'].map((x,i)=>`<article><div class="journal-image tone-${['clay','sunset','grove'][i]}"></div><p>${['Design','Living','Architecture'][i]} · Jul ${12-i*3}, 2026</p><h3>${x}</h3><a href="/journal">Read story ↗</a></article>`).join('')}</div></section>
${contactBlock()}`}
function contactBlock(){return `<section class="contact-block tone-night"><div><p class="eyebrow">Begin a conversation</p><h2>Your next chapter<br>begins with a <i>conversation.</i></h2></div><a class="light-btn" href="/contact">Schedule a viewing <b>↗</b></a></section>`}
function propertiesPage(){ return `<section class="inner-hero"><p class="eyebrow">The collection</p><h1>Homes of <i>distinction.</i></h1><p>Our current selection of considered residences across remarkable markets.</p></section><section class="listing section"><form id="filters"><input name="query" placeholder="Search residences"><select name="type"><option value="">All property types</option>${[...new Set(properties.map(x=>x.type))].map(x=>`<option>${x}</option>`).join('')}</select><select name="beds"><option value="">Bedrooms</option><option value="3">3+ beds</option><option value="4">4+ beds</option><option value="5">5+ beds</option></select><select name="sort"><option value="new">Newest</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select><button class="dark-btn">Apply</button><button type="reset" class="text-btn">Reset</button></form><p id="result-count">6 residences</p><div id="listing-grid" class="listing-grid">${properties.map(card).join('')}</div></section>`}
function detail(slug){const p=properties.find(x=>x.slug===slug);if(!p)return notFound();return `<section class="detail-hero tone-${p.tone}"><a href="/properties" class="back">← All properties</a><div><p>${p.tag} · ${p.city}</p><h1>${p.title}</h1><strong>${money(p.price)}</strong></div></section><section class="section detail-intro"><div><p class="eyebrow">The residence</p><h2>${p.desc}</h2></div><div class="facts"><p><b>${p.beds}</b> Bedrooms</p><p><b>${p.baths}</b> Bathrooms</p><p><b>${p.sqft.toLocaleString()}</b> Sq. Ft.</p><p><b>${p.type}</b> Property type</p></div></section><section class="gallery section"><div class="tone-${p.tone}"></div><div class="tone-sunset"></div><div class="tone-night"></div></section><section class="section amenities"><p class="eyebrow">Considered details</p><h2>A residence composed<br>for the <i>everyday.</i></h2><div>${['Chef’s kitchen','Indoor–outdoor living','Custom millwork','Private garden','Smart home system','Secure parking'].map(x=>`<p>✦ ${x}</p>`).join('')}</div></section><section class="inquiry section"><div><p class="eyebrow">Private viewing</p><h2>Experience it<br><i>in person.</i></h2></div>${inquiryForm()}</section><section class="section"><div class="section-head"><p class="eyebrow">Similar residences</p><a class="line-link" href="/properties">View collection ↗</a></div><div class="feature-grid">${properties.filter(x=>x.slug!==slug).slice(0,3).map(card).join('')}</div></section>`}
function inquiryForm(){return `<form class="inquiry-form"><label>Full name<input required name="name"></label><label>Email address<input required type="email" name="email"></label><label>Interest<select><option>Buying</option><option>Selling</option><option>Investing</option></select></label><label class="wide">Message<textarea placeholder="Tell us a little about what you’re looking for."></textarea></label><input class="honeypot" tabindex="-1" autocomplete="off"><label class="check"><input type="checkbox" required>I agree to be contacted by Aurelia Estates.</label><button class="dark-btn">Send enquiry <b>↗</b></button><p class="form-result" aria-live="polite"></p></form>`}
function infoPage(kind){
  const copy={about:['A point of view,<br><i>well placed.</i>','Aurelia is an independent residential advisory built around a simple conviction: exceptional homes deserve exceptional representation.'],services:['The art of<br><i>considered advice.</i>','A tailored practice for property owners, buyers, and investors who value clarity and discretion.'],journal:['A life lived<br><i>beautifully.</i>','Essays, addresses, and observations from the places that stay with us.'],contact:['Let’s begin with<br><i>what matters.</i>','Tell us what you are looking for. A member of our team will respond personally.']}[kind];
  const intro=`<section class="inner-hero"><p class="eyebrow">Aurelia Estates</p><h1>${copy[0]}</h1><p>${copy[1]}</p></section>`;
  if(kind==='contact') return intro+`<section class="section contact-page">${inquiryForm()}<aside><p class="eyebrow">Concierge</p><h3>hello@aurelia.demo<br>+1 212 555 0184</h3><p>New York<br>Los Angeles<br>Miami</p></aside></section>`;
  const feature=`<section class="section editorial"><div class="tone-${kind==='journal'?'clay':'grove'}"></div><article><p class="eyebrow">Our approach</p><h2>Thoughtful work, <i>lasting impact.</i></h2><p>We work with a limited number of clients at a time, allowing every decision to receive the care it deserves. This is demo copy, ready to be replaced with your own narrative.</p><a class="dark-btn" href="/contact">Start a conversation ↗</a></article></section>`;
  if(kind!=='journal') return intro+feature;
  const articles=['The modern garden room','The allure of a long view','A home with a memory'].map((x,i)=>`<article><div class="journal-image tone-${['sunset','water','night'][i]}"></div><p>Journal · Jul 2026</p><h3>${x}</h3><a href="/journal">Read story ↗</a></article>`).join('');
  return intro+feature+`<section class="journal section"><div class="journal-grid">${articles}</div></section>`;
}
function notFound(){return `<section class="not-found"><p class="eyebrow">404</p><h1>Not every path<br>leads <i>home.</i></h1><a class="dark-btn" href="/properties">Explore properties ↗</a></section>`}
function render(){let path=location.pathname.replace(/\/$/,'')||'/';let content=path==='/'?home():path==='/properties'?propertiesPage():path.startsWith('/properties/')?detail(path.split('/').pop()):['/about','/services','/journal','/contact'].includes(path)?infoPage(path.slice(1)):notFound();$('#main').innerHTML=content;$('#footer').innerHTML=footer();wire();window.scrollTo(0,0)}
function wire(){document.querySelectorAll('a[href^="/"]').forEach(a=>a.addEventListener('click',e=>{if(e.metaKey||e.ctrlKey)return;e.preventDefault();history.pushState({},'',a.href);render()}));$('#top')?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));$('#quick-search')?.addEventListener('submit',e=>{e.preventDefault();let f=new FormData(e.target),q=new URLSearchParams(f);history.pushState({},'',`/properties?${q}`);render()});let filters=$('#filters');filters?.addEventListener('input',()=>{let fd=new FormData(filters),items=[...properties];if(fd.get('query'))items=items.filter(x=>x.title.toLowerCase().includes(fd.get('query').toLowerCase())||x.city.toLowerCase().includes(fd.get('query').toLowerCase()));if(fd.get('type'))items=items.filter(x=>x.type===fd.get('type'));if(fd.get('beds'))items=items.filter(x=>x.beds>=+fd.get('beds'));if(fd.get('sort')==='low')items.sort((a,b)=>a.price-b.price);if(fd.get('sort')==='high')items.sort((a,b)=>b.price-a.price);$('#listing-grid').innerHTML=items.map(card).join('');$('#result-count').textContent=`${items.length} ${items.length===1?'residence':'residences'}`});filters?.addEventListener('reset',()=>setTimeout(()=>filters.dispatchEvent(new Event('input')),0));document.querySelectorAll('.inquiry-form').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();let r=f.querySelector('.form-result');r.textContent='Thank you. Your enquiry has been received; connect an API or CRM here for delivery.';f.reset()}));}
$('.menu').addEventListener('click',()=>{let open=document.body.classList.toggle('menu-open');$('.menu').setAttribute('aria-expanded',open);$('.mobile-menu').setAttribute('aria-hidden',!open)});addEventListener('popstate',render);addEventListener('scroll',()=>$('#nav').classList.toggle('scrolled',scrollY>20),{passive:true});render();
